// svelte/examples/todo-list/TodoList.svelte
<script>
  import Todo from "./Todo.svelte";

  export let todos;
  export let onCheck;
  export let onUncheck;

  $: openTodos = todos.filter(todo => !todo.done);
  $: doneTodos = todos.filter(todo => todo.done);
</script>

<div>
  <h2>Todo</h2>
  <ul>
    {#each openTodos as todo}
      <li>
        <Todo item={todo} {onCheck} />
      </li>
    {/each}
  </ul>
  <h2>Done</h2>
  <ul>
    {#each doneTodos as todo}
      <li>
        <Todo item={todo} {onUncheck} />
      </li>
    {/each}
  </ul>
</div>

// hyperapp/examples/todo-list/TodoList.jsx
import { h } from "hyperapp";
import { Todo } from './Todo.jsx';

export const TodoList = ({ todos, onCheck, onUncheck }) => {
    const doneTodos = todos.filter(todo => todo.done);
    const openTodos = todos.filter(todo => !todo.done);
    return (
        <div>
            <h2>Todo</h2>
            <ul>
                {openTodos.map(todo => <li><Todo item={todo} onCheck={onCheck} /></li>)}
            </ul>
            <h2>Done</h2>
            <ul>
                {doneTodos.map(todo => <li><Todo item={todo} onUncheck={onUncheck} /></li>)}
            </ul>
        </div>);
};
