// hyperapp/examples/todo-list/TodoInput.jsx
import { h } from "hyperapp";

const parseTitle = e => {
    e.preventDefault();
    const input = e.target.children[0];
    const value = input.value.trim();

    if(!value.length) {
        return null;
    }
    else {
        input.value = null; 
    }

    return { title: value, done: false }
}

export const TodoInput = ({ onAdd }) => {
    return (
        <form onsubmit={[onAdd, parseTitle]}>
            <input autofocus
                autocomplete="off"
                type="text"
                placeholder="Add Todo" />
        </form>
    )
};

// svelte/examples/todo-list/TodoInput.svelte
<script>
  export let onAdd;

  const onSubmit = e => {
    e.preventDefault();

    const input = e.target.children[0];
    const value = input.value.trim();

    if(!value || !value.length || !onAdd){
      return;
    }
    input.value = null;
    onAdd({ title: value, done: false });
  }
</script>

<form on:submit={onSubmit}>
  <input autofocus autocomplete="off" type="text" placeholder="Add Todo" />
</form>
